# Generated by Django 2.2.4 on 2019-08-24 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0066_pyproductwebcategory_parent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PySaleOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('fc', models.DateTimeField(auto_now_add=True, null=True)),
                ('fm', models.DateTimeField(auto_now=True, null=True)),
                ('uc', models.IntegerField(blank=True, null=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('date_order', models.DateTimeField(auto_now=True, null=True)),
                ('amount_untaxec', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Neto')),
                ('amount_taxt', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Impuestos')),
                ('amount_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('description', models.TextField(blank=True, null=True)),
                ('state', models.CharField(choices=[('draft', 'Borrador'), ('open', 'Consumible'), ('cancel', 'Servicio')], default='draft', max_length=64)),
                ('partner_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.PyPartner')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
