# Generated by Django 2.2.4 on 2019-08-30 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pysaleorder',
            name='amount_taxt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Impuestos'),
        ),
        migrations.AlterField(
            model_name='pysaleorder',
            name='amount_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='pysaleorder',
            name='amount_untaxec',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto Neto'),
        ),
        migrations.AlterField(
            model_name='pysaleorder',
            name='date_order',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='pysaleorder',
            name='state',
            field=models.CharField(choices=[('draft', 'Borrador'), ('open', 'Consumible'), ('cancel', 'Servicio'), ('confirmada', 'confirmada')], default='draft', max_length=64),
        ),
    ]
