# Generated by Django 2.2.4 on 2019-08-30 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_auto_20190829_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pysaleorderdetail',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.PyProduct'),
            preserve_default=False,
        ),
    ]
