# Generated by Django 2.2.4 on 2019-08-15 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_pycomuna_pyregion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pycompany',
            name='country_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.PyCountry'),
        ),
    ]
