# Generated by Django 2.2.4 on 2019-08-15 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_pycompany_country_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pycompany',
            name='comuna_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.PyComuna'),
        ),
        migrations.AddField(
            model_name='pycompany',
            name='region_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.PyRegion'),
        ),
    ]
