# Generated by Django 2.2.4 on 2019-08-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_pypartner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pypartner',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pypartner',
            name='email',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='pypartner',
            name='giro',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='pypartner',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pypartner',
            name='rut',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='pypartner',
            name='street',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pypartner',
            name='street_2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
