# Generated by Django 2.2.4 on 2019-08-15 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20190815_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='PyProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('code', models.CharField(max_length=80)),
                ('price', models.IntegerField()),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='pycompany',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pycompany',
            name='email',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='pycompany',
            name='giro',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='pycompany',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pycompany',
            name='rut',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='pycompany',
            name='street',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pycompany',
            name='street_2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
