# Generated by Django 2.2.4 on 2019-08-15 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20190815_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pyproduct',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
        migrations.AlterField(
            model_name='pyproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
