# Generated by Django 2.2.4 on 2019-08-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20190815_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyproduct',
            name='bar_code',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
