# Generated by Django 2.2.4 on 2019-08-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_pyproduct_bar_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pypartner',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='pypartner',
            name='email',
            field=models.CharField(blank=True, max_length=40, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='pypartner',
            name='giro',
            field=models.CharField(blank=True, max_length=80, verbose_name='Giro'),
        ),
        migrations.AlterField(
            model_name='pypartner',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='pypartner',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='pypartner',
            name='rut',
            field=models.CharField(blank=True, max_length=12, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='pypartner',
            name='street',
            field=models.CharField(blank=True, max_length=100, verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='pypartner',
            name='street_2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Calle 2'),
        ),
        migrations.AlterField(
            model_name='pyproduct',
            name='bar_code',
            field=models.CharField(blank=True, max_length=80, verbose_name='Cod. Barras'),
        ),
        migrations.AlterField(
            model_name='pyproduct',
            name='code',
            field=models.CharField(blank=True, max_length=80, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='pyproduct',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='pyproduct',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='pyproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Precio'),
        ),
    ]
