# Generated by Django 2.2.4 on 2019-08-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20190816_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='pypartner',
            name='customer',
            field=models.BooleanField(default=False, verbose_name='Es cliente'),
        ),
        migrations.AddField(
            model_name='pypartner',
            name='provider',
            field=models.BooleanField(default=False, verbose_name='Es proveedor'),
        ),
    ]
