# Generated by Django 2.2.4 on 2019-08-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_pyemployee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pyemployee',
            name='first_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='pyemployee',
            name='last_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='pyemployee',
            name='name2',
            field=models.CharField(blank=True, max_length=80, verbose_name='Segundo Nombre'),
        ),
    ]
