# Generated by Django 2.2.4 on 2019-08-17 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20190816_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='PyDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
            ],
        ),
    ]
