# Generated by Django 2.2.4 on 2019-08-17 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_pydepartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PyLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
            ],
        ),
        migrations.AlterField(
            model_name='pypartner',
            name='customer',
            field=models.BooleanField(default=True, verbose_name='Es cliente'),
        ),
        migrations.AlterField(
            model_name='pypartner',
            name='provider',
            field=models.BooleanField(default=True, verbose_name='Es proveedor'),
        ),
    ]
