# Generated by Django 2.2.4 on 2019-08-17 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20190817_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyproduct',
            name='web_active',
            field=models.BooleanField(default=False, verbose_name='Web'),
        ),
    ]
