# Generated by Django 2.2.4 on 2019-08-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_pyarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='pypartner',
            name='for_invoice',
            field=models.BooleanField(default=True, verbose_name='Para Facturar'),
        ),
    ]
