# Generated by Django 2.2.4 on 2019-08-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_pypartner_for_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pycompany',
            name='email',
            field=models.EmailField(blank=True, max_length=40),
        ),
    ]
