# Generated by Django 2.2.4 on 2019-08-17 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0024_auto_20190817_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='pypartner',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pypartne_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pypartner',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created on'),
            preserve_default=False,
        ),
    ]
