# Generated by Django 2.2.4 on 2019-08-17 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_auto_20190817_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pypartner',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pypartner_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
