# Generated by Django 2.2.4 on 2019-08-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_auto_20190817_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='pypartner',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
