# Generated by Django 2.2.4 on 2019-08-17 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_auto_20190817_2106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pyproduct',
            options={'ordering': ['created_on']},
        ),
    ]
