# Generated by Django 2.2.4 on 2019-08-18 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_auto_20190817_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyproduct',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
