# Generated by Django 2.2.4 on 2019-08-18 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_baseuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseUser',
        ),
    ]
