# Generated by Django 2.2.4 on 2019-08-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_baseconfig_main_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseconfig',
            name='slogan',
            field=models.CharField(blank=True, max_length=250, verbose_name='Eslogan'),
        ),
    ]
