# Generated by Django 2.2.4 on 2019-08-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_baseconfig_slogan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseconfig',
            name='slogan',
        ),
        migrations.AddField(
            model_name='pycompany',
            name='slogan',
            field=models.CharField(blank=True, max_length=250, verbose_name='Eslogan'),
        ),
    ]
