# Generated by Django 2.2.4 on 2019-08-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_auto_20190818_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='pycompany',
            name='social_facebook',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pycompany',
            name='social_instagram',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pycompany',
            name='social_linkedin',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
