# Generated by Django 2.2.4 on 2019-08-19 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_auto_20190818_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseconfig',
            name='open_menu',
            field=models.BooleanField(default=True, verbose_name='Menu Abierto'),
        ),
    ]
