# Generated by Django 2.2.4 on 2019-08-19 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_baseconfig_open_menu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PyDepartment',
        ),
        migrations.DeleteModel(
            name='PyEmployee',
        ),
    ]
