# Generated by Django 2.2.4 on 2019-08-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_auto_20190819_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseconfig',
            name='load_data',
            field=models.BooleanField(default=False, verbose_name='Data Cargada'),
        ),
    ]
