# Generated by Django 2.2.4 on 2019-08-20 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_auto_20190820_0234'),
        ('base', '0048_baseconfig_load_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='pypartner',
            name='campaign_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.PyCampaign'),
        ),
        migrations.AddField(
            model_name='pypartner',
            name='channel_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.PyChannel'),
        ),
    ]
