# Generated by Django 2.2.4 on 2019-08-20 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_pyproductwebcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyproduct',
            name='web_category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.PyProductWebCategory'),
        ),
    ]
