# Generated by Django 2.2.4 on 2019-08-20 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_pylog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PyArticle',
        ),
        migrations.DeleteModel(
            name='PyLead',
        ),
    ]
