# Generated by Django 2.2.4 on 2019-08-21 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0053_auto_20190820_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pypartner',
            name='giro',
        ),
        migrations.RemoveField(
            model_name='pypartner',
            name='rut',
        ),
    ]
