# Generated by Django 2.2.4 on 2019-08-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0055_pycron'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pycron',
            name='model_name',
            field=models.CharField(max_length=40, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='pycron',
            name='number_call',
            field=models.IntegerField(default=-1, verbose_name='Número de llamadas'),
        ),
    ]
