# Generated by Django 2.2.4 on 2019-08-23 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_auto_20190821_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pycompany',
            name='rut',
        ),
    ]
