# Generated by Django 2.2.4 on 2019-08-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0063_auto_20190823_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pycompany',
            name='uc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pycomuna',
            name='uc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pycountry',
            name='uc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pycron',
            name='uc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pylog',
            name='uc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pypartner',
            name='uc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pyproduct',
            name='uc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pyproductcategory',
            name='uc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pyproductwebcategory',
            name='uc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pyregion',
            name='uc',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
