# Generated by Django 2.2.4 on 2019-08-24 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0064_auto_20190823_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyproductcategory',
            name='parent_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.PyProductCategory'),
        ),
    ]
