# Generated by Django 2.2.4 on 2019-08-27 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0068_pycurrency'),
    ]

    operations = [
        migrations.AddField(
            model_name='pycompany',
            name='currency_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.PyCurrency'),
        ),
    ]
