# Generated by Django 2.2.4 on 2019-08-28 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0069_pycompany_currency_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pypartner',
            name='not_email',
            field=models.BooleanField(default=True, verbose_name='No Email'),
        ),
    ]
