# Generated by Django 2.2.4 on 2019-08-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0071_auto_20190828_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pyproduct',
            name='bar_code',
            field=models.CharField(blank=True, max_length=80, verbose_name='Bar Code'),
        ),
        migrations.AlterField(
            model_name='pyproduct',
            name='code',
            field=models.CharField(blank=True, max_length=80, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='pyproduct',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cost'),
        ),
        migrations.AlterField(
            model_name='pyproduct',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='pyproduct',
            name='img',
            field=models.ImageField(default='default.png', upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='pyproduct',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='pyproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='pyproduct',
            name='type',
            field=models.CharField(choices=[('product', 'Almacenable'), ('consu', 'Consumible'), ('service', 'Servicio')], default='consu', max_length=64, verbose_name='type'),
        ),
    ]
