# Generated by Django 2.2.4 on 2019-08-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0074_pyapp_installed'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyapp',
            name='website',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='pyapp',
            name='installed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
