# Generated by Django 2.2.4 on 2019-08-31 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0077_pyapp_fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyapp',
            name='version',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Version'),
        ),
    ]
