# Generated by Django 2.2.4 on 2019-09-02 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0078_pyapp_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pycompany',
            name='comuna_id',
        ),
        migrations.RemoveField(
            model_name='pycompany',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='pycompany',
            name='region_id',
        ),
        migrations.DeleteModel(
            name='PyComuna',
        ),
        migrations.DeleteModel(
            name='PyRegion',
        ),
    ]
