# Generated by Django 2.2.4 on 2019-09-02 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0079_auto_20190901_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pycountry',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Name'),
        ),
    ]
