# Generated by Django 2.2.4 on 2019-09-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0080_auto_20190901_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyapp',
            name='sequence',
            field=models.IntegerField(default=100, verbose_name='Sequence'),
        ),
    ]
