# Generated by Django 2.2.4 on 2019-08-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PyCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('code', models.CharField(max_length=13, verbose_name='Código')),
            ],
        ),
        migrations.AddField(
            model_name='pychannel',
            name='code',
            field=models.CharField(blank=True, max_length=13, verbose_name='Código'),
        ),
    ]
