# Generated by Django 2.2.4 on 2019-08-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_auto_20190820_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pychannel',
            name='code',
            field=models.CharField(max_length=13, verbose_name='Código'),
        ),
    ]
