# Generated by Django 2.2.4 on 2019-08-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_auto_20190820_0234'),
    ]

    operations = [
        migrations.CreateModel(
            name='PyMform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
        ),
    ]
