# Generated by Django 2.2.4 on 2019-08-20 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_pymform'),
    ]

    operations = [
        migrations.AddField(
            model_name='pymform',
            name='campaign_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.PyCampaign'),
        ),
    ]
