# Generated by Django 2.2.4 on 2019-08-17 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0002_auto_20190817_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pytask',
            name='income',
        ),
        migrations.CreateModel(
            name='PyProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('note', models.TextField(blank=True, null=True)),
                ('income', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ingreso')),
                ('state', models.CharField(choices=[('nuevo', 'Nuevo'), ('trabajando', 'Trabajando'), ('finalizado', 'Finalizado')], default='nuevo', max_length=64)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
