# Generated by Django 2.2.4 on 2019-08-17 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0004_remove_pyproject_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='PyBug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('note', models.TextField(blank=True, null=True)),
                ('state', models.CharField(choices=[('nuevo', 'Nuevo'), ('trabajando', 'Trabajando'), ('finalizado', 'Finalizado')], default='nuevo', max_length=64)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
