# Generated by Django 2.2.4 on 2019-08-17 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_pybug'),
    ]

    operations = [
        migrations.AddField(
            model_name='pytask',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.PyProject'),
        ),
    ]
