# Generated by Django 2.2.4 on 2019-08-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_pylead_partner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pylead',
            name='income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ingreso'),
        ),
    ]
