# Generated by Django 2.2.4 on 2019-08-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_pylead_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='PyStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
            ],
        ),
    ]
