# Generated by Django 2.2.4 on 2019-08-17 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_pystage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pylead',
            name='stage_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.PyStage'),
        ),
    ]
