# Generated by Django 2.2.4 on 2019-08-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20190823_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pystage',
            name='uc',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
