# Generated by Django 2.2.4 on 2019-08-28 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_auto_20190823_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='pylead',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
