# Generated by Django 2.2.4 on 2019-08-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_pyaccountplan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyaccountplan',
            name='reconcile',
            field=models.BooleanField(default=False, verbose_name='Conciliación'),
        ),
    ]
