# Generated by Django 2.2.4 on 2019-08-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_pyaccountplan_reconcile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PyAccountMove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, verbose_name='Código')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('state', models.CharField(choices=[('draft', 'Borrador'), ('posted', 'Validado')], default='draft', max_length=64)),
            ],
        ),
    ]
