# Generated by Django 2.2.4 on 2019-08-21 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_pyaccountmoveline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pyaccountmoveline',
            name='move',
            field=models.ForeignKey(on_delete='cascade', related_name='lines', related_query_name='line', to='account.PyAccountMove'),
        ),
    ]
