# Generated by Django 2.2.4 on 2019-08-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20190821_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pyaccountmoveline',
            name='move',
            field=models.ForeignKey(on_delete='cascade', related_name='lines', to='account.PyAccountMove'),
        ),
    ]
