# Generated by Django 2.2.4 on 2019-08-19 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190818_0205'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PyArticle',
            new_name='PyPost',
        ),
    ]
