# Generated by Django 2.2.4 on 2019-08-19 04:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20190819_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='pypost',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
