# Generated by Django 2.2.4 on 2019-08-20 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_pypost_created_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pypost',
            old_name='description',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='pypost',
            old_name='name',
            new_name='title',
        ),
    ]
