# Generated by Django 2.2.4 on 2019-08-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_websiteconfig_under_construction'),
    ]

    operations = [
        migrations.AddField(
            model_name='pypost',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='pypost',
            name='fc',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pypost',
            name='fm',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='pypost',
            name='uc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pypost',
            name='um',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websiteconfig',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='websiteconfig',
            name='fc',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='websiteconfig',
            name='fm',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='websiteconfig',
            name='uc',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websiteconfig',
            name='um',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
