# Generated by Django 2.2.4 on 2019-08-27 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_webpaymentmethod'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WebPaymentMethod',
            new_name='PyWebPaymentMethod',
        ),
    ]
