# Generated by Django 2.2.4 on 2019-08-28 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20190827_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteconfig',
            name='show_chat',
            field=models.BooleanField(default=False, verbose_name='Mostrar Chat'),
        ),
    ]
