# Generated by Django 2.2.4 on 2019-08-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_websiteconfig_show_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteconfig',
            name='show_blog',
            field=models.BooleanField(default=False, verbose_name='Show Blog'),
        ),
        migrations.AlterField(
            model_name='websiteconfig',
            name='show_chat',
            field=models.BooleanField(default=False, verbose_name='Show chat'),
        ),
        migrations.AlterField(
            model_name='websiteconfig',
            name='show_shop',
            field=models.BooleanField(default=False, verbose_name='Show Shop'),
        ),
        migrations.AlterField(
            model_name='websiteconfig',
            name='under_construction',
            field=models.BooleanField(default=False, verbose_name='Under Construction'),
        ),
    ]
