# Generated by Django 2.2.4 on 2019-08-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PyEconomicalActivitie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('code', models.CharField(blank=True, max_length=80, verbose_name='Código')),
            ],
        ),
    ]
