# Generated by Django 2.2.4 on 2019-08-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pyeconomicalactivitie',
            name='code',
            field=models.CharField(max_length=255, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='pyeconomicalactivitie',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
