# Generated by Django 2.2.4 on 2019-08-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_auto_20190823_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pypos',
            name='uc',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
