# Generated by Django 2.2.4 on 2019-08-30 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20190829_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='pytrigger',
            name='answer',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='pytrigger',
            name='question',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='pytrigger',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Name'),
        ),
    ]
