# Generated by Django 2.2.4 on 2019-08-30 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20190829_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pytrigger',
            name='name',
        ),
    ]
