# Generated by Django 2.2.4 on 2019-08-30 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_pytrigger_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pytrigger',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='Name'),
        ),
    ]
