# Generated by Django 2.2.4 on 2019-08-30 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20190829_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pytrigger',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='pytrigger',
            name='question',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Question'),
        ),
    ]
