# Generated by Django 2.2.4 on 2019-08-30 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20190829_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='pytrigger',
            name='init',
            field=models.BooleanField(default=False, verbose_name='Init'),
        ),
    ]
