# Generated by Django 2.2.4 on 2019-08-30 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_pytrigger_init'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyvisitor',
            name='sid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SID'),
        ),
        migrations.AlterField(
            model_name='pyvisitor',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Nombre'),
        ),
        migrations.CreateModel(
            name='PyChatHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('fc', models.DateTimeField(auto_now_add=True, null=True)),
                ('fm', models.DateTimeField(auto_now=True, null=True)),
                ('uc', models.IntegerField(blank=True, null=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('message', models.CharField(max_length=500, verbose_name='Mensaje')),
                ('response', models.BooleanField(default=False, verbose_name='Respuesta')),
                ('datetime', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Visitante', to='chat.PyVisitor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
